version: '3.3'
services:
  reactjs:
    container_name: reactjs
    image: 'node:latest'
    working_dir: /home/reactjs/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - '.:/home/reactjs/app'
    environment:
      - CHOKIDAR_USEPOLLING=true